theme = "catppuccin_mocha"

[editor]
true-color = true
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
C-y = ":sh zellij run -n Yazi -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open ."
"Y" = ":clipboard-yank"

[keys.select]
"Y" = ":clipboard-yank"